/*
 * decaffeinate suggestions:
 * DS206: Consider reworking classes to avoid initClass
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/main/docs/suggestions.md
 */
const TrueDamageAction = require('./trueDamageAction');
const _ = require('underscore');

/*
  Hurting damage actions are generated by the hurting phase of the game when a player has no more cards in the deck.
*/
class HurtingDamageAction extends TrueDamageAction {
  static initClass() {
    this.type = 'HurtingDamageAction';

    this.prototype.damageAmount = 2;
  }

  constructor() {
    super(...arguments);
  }
}
HurtingDamageAction.initClass();

module.exports = HurtingDamageAction;
