/*
 * decaffeinate suggestions:
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/main/docs/suggestions.md
 */
const TrueDamageAction = require('./trueDamageAction');
const _ = require('underscore');

/*
  Hurting damage actions are generated by the hurting phase of the game when a player has no more cards in the deck.
*/
class HurtingDamageAction extends TrueDamageAction {
  declare damageAmount: any;

  static type = 'HurtingDamageAction';

  constructor() {
    super(...arguments);
  }
}
HurtingDamageAction.prototype.damageAmount = 2;

module.exports = HurtingDamageAction;
