name: build_app

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - app/**
      - config/**
      - gulp/**
      - gulpfile.babel.js
      - package.json
      - pnpm-lock.yaml

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: install system dependencies
      run: sudo apt install -y libpng-dev

    - name: install pnpm
      uses: pnpm/action-setup@v4

    - name: install node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: install node dependencies
      run: pnpm install --frozen-lockfile

    - name: install typescript dependencies
      run: pnpm tsc:chroma-js

    - name: build the app
      run: pnpm build
      env:
        FIREBASE_URL: "https://test-url.firebaseio.com/"
