name: integration_tests

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - app/**
      - config/**
      - gulp/**
      - gulpfile.babel.js
      - package.json
      - server/**
      - test/**
      - worker/**
      - pnpm-lock.yaml

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    container: node:24-bookworm-slim
    services:
      redis:
        image: redis:6
      db:
        image: postgres:13
        env:
          POSTGRES_USER: duelyst
          POSTGRES_PASSWORD: duelyst
          POSTGRES_DB: duelyst

    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: install pnpm
      uses: pnpm/action-setup@v4

    - name: install node dependencies
      run: pnpm install --frozen-lockfile

    - name: run database migrations
      run: pnpm migrate:latest
      env:
        NODE_ENV: development
        POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"

    - name: run integration tests
      run: pnpm test:integration:misc
      env:
        REDIS_HOST: redis
        POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
        # TODO: Create a Firebase Realtime Database for CI.
        FIREBASE_URL: "https://test-url.firebaseio.com/"
