name: lint_coffeescript

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - app/**.coffee
      #- cli/**.coffee
      #- scripts/**.coffee
      - server/**.coffee
      - worker/**.coffee

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: install pnpm
      uses: pnpm/action-setup@v4

    - name: install node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: install node dependencies
      run: pnpm install --frozen-lockfile

    - name: compile typescript dependencies
      run: pnpm tsc:chroma-js

    - name: lint coffeescript code
      run: pnpm lint:coffee app server worker # excludes cli, scripts
