name: unit_tests

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - app/**
      - config/**
      - gulp/**
      - gulpfile.babel.js
      - package.json
      - server/**
      - test/**
      - worker/**
      - pnpm-lock.yaml

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: install system dependencies
      run: sudo apt install -y libpng-dev

    - name: install pnpm
      uses: pnpm/action-setup@v4

    - name: install node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: install node dependencies
      run: pnpm install --frozen-lockfile

    - name: run unit tests
      run: pnpm test:unit
